"""org_setup_wizard_fields

Revision ID: 312499652146
Revises: aa624f736603
Create Date: 2026-07-05 12:35:45.010471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '312499652146'
down_revision: Union[str, None] = 'aa624f736603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: the autogenerated drop_index for knowledge_chunks_embedding_idx was
    # removed — that HNSW index was created via raw SQL in the initial
    # migration and isn't represented in SQLAlchemy metadata, so autogenerate
    # sees it as "unknown" and wants to drop it. It must stay.
    op.add_column('organizations', sa.Column('address', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column(
        'organizations',
        sa.Column(
            'setup_progress',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        'organizations',
        sa.Column(
            'booking_config',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text('\'{"services": [], "calendar_enabled": false}\'::jsonb'),
        ),
    )
    op.add_column(
        'organizations',
        sa.Column(
            'system_prompts',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'system_prompts')
    op.drop_column('organizations', 'booking_config')
    op.drop_column('organizations', 'setup_progress')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'address')
    # ### end Alembic commands ###
