"""voice call tracking and retell api key provider

Revision ID: 8dd812fcd5b9
Revises: c26129c7e775
Create Date: 2026-07-08 16:38:14.070650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd812fcd5b9'
down_revision: Union[str, None] = 'c26129c7e775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('retell_call_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('call_duration_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_retell_call_id'), 'conversations', ['retell_call_id'], unique=True)
    # ### end Alembic commands ###
    # Not autogenerated — alembic's autogenerate doesn't diff native Postgres
    # enum values. Added manually to back ApiKeyProvider.retell.
    op.execute("ALTER TYPE api_key_provider ADD VALUE IF NOT EXISTS 'retell'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_retell_call_id'), table_name='conversations')
    op.drop_column('conversations', 'call_duration_seconds')
    op.drop_column('conversations', 'retell_call_id')
    # ### end Alembic commands ###
    # Postgres has no ALTER TYPE ... DROP VALUE — a full downgrade of the enum
    # would require rebuilding the type, which isn't warranted for a dev-time
    # rollback of this migration. Left as a no-op, matching how other enum
    # additions in this project's migration history are handled.
