"""whatsapp_message_delivery_tracking

Revision ID: c26129c7e775
Revises: 312499652146
Create Date: 2026-07-08 14:06:28.504019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26129c7e775'
down_revision: Union[str, None] = '312499652146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('whatsapp_message_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('delivery_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_whatsapp_message_id'), 'messages', ['whatsapp_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_whatsapp_message_id'), table_name='messages')
    op.drop_column('messages', 'delivery_status')
    op.drop_column('messages', 'whatsapp_message_id')
    # ### end Alembic commands ###
